### PR TITLE
Build for aarch64 and dramatically reduce size of package

### PR DESCRIPTION
**Pull request by hfiguiere**
- use QtWebEngine base app
- build PyQt from source

Tested on both regular PC and RasberryPi (64-bits)

### CODE REVIEW

**Comment by hfiguiere** [comment]
Build this way the x86_64 flatpak is 130+MB lighter.

**Comment by hfiguiere** [comment]
This latest patch shave another 100MB

**Comment by hfiguiere** [comment]
@LukeBriggsDev any chance to get this merged?

**Comment by LukeBriggsDev** [comment]
@hfiguiere Hi! Sorry it took so long to see this. Must have missed the original notification and everything just went into a thread

Anyway, thanks for your wonderful work and I have merged it into the main repo.

**Pull request merged**
